baseURL = 'https://bugratezcan.com/'
title = 'bugra tezcan'
theme = 'hugo-trainsh'
disableKinds = ["RSS"]
defaultContentLanguage = 'en'

[params]
  mainSections = ["post"]

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1

    [[languages.en.menus.main]]
      name = 'Home'
      pageRef = '/'
      weight = 1

    [[languages.en.menus.main]]
      name = 'Blog'
      pageRef = '/post'
      weight = 2

    [[languages.en.menus.main]]
      name = 'Me'
      pageRef = '/me'
      weight = 3

[module]
  [module.hugoVersion]
    extended = true
    min = '0.114.0'

